### ISSUE TITLE
Null in Queriers

### ISSUE THREAD

**Issue by Reyhanejaffari** [umutozel/DynamicQueryable#1]
this query does not work               
organizationalRoles = organizationalRoles.Where("(Parent!=null ? parent.Name:Title)");
how did you handle null values in code

**Comment by Reyhanejaffari** [comment]
i add 
 if (_keywords.TryGetValue(_token.Text, out value))
            {
                var type = value as Type;
                if (type != null) return ParseTypeAccess(type);
                if (value == NullLiteral)
                {
                    Expression expr = value as Expression;
                    NextToken();
                    return expr;
                }
                if ((string)value == KeywordIt) return ParseIt();
                if ((string)value == KeywordOuterIt) return ParseOuterIt();
                if ((string)value == KeywordIif) return ParseIif();
                if ((string)value == KeywordNew) return ParseNew();
                NextToken();
                return null;
            }
in Expression ParseIdentifier() and it works.
is this code true?

**Comment by umutozel** [comment]
Sorry for the late reply, I missed the notification I believe.

You should use a comparison in your expression, it should work with that, I am adding a new unit test right now;

_query.Where("(Id == 5 ? 1 : (int?)null) != null")

and it's working.

I believe your code should be like this;

organizationalRoles.Where("(Parent!=null ? parent.Name:Title) != null");

**Comment by gbreen12** [comment]
I'm trying to do something similar and it doesn't seem to work:

`query.OrderBy($"{ob.Field}==null")`

Any ideas?

**Comment by gbreen12** [comment]
Looks like I just needed to change it to:

`query.OrderBy($"x => !x.{ob.Field}.HasValue")`

**Comment by umutozel** [comment]
@gbreen12 first one should work, I'll look into it.
